abTestSource: swrve
LEVEL_SWAP:
  CLONES:
    "1": -40
    "2": -39
    "3": -38
    "4": -37
    "5": -36
    "6": -35
    "7": -34
    "8": -33
    "9": -32
    "10": -31
    "11": -30
    "12": -29
    "13": -28
    "14": -27
    "15": -26
    "16": -25
    "17": -24
    "18": -23
    "19": -22
    "20": -21
  EASIER:
    "1": -20
    "2": -19
    "3": -18
    "4": -17
    "5": -16
    "6": -15
    "7": -14
    "8": -13
    "9": -12
    "10": -11
    "11": -10
    "12": -9
    "13": -8
    "14": -7
    "15": -6
    "16": -5
    "17": -4
    "18": -3
    "19": -2
    "20": -1
