bragging: false
lives: false
xp: false
demoGame: false
dailyBonus: false
invites: false
powerups: false
luckySpin: false
progressionMap: false
currency: false
gifts: false
tango: false
tutorialFriends: false
facebook: false
theme: true
themeShop: false
characterShop: true
teamShop: false
friendPoints: false
weebySimpleSocial: true
